ALTER TABLE "Lender"
ALTER COLUMN "lenderRating" TYPE DOUBLE PRECISION,
ALTER COLUMN "lenderRating" SET DEFAULT 0;

ALTER TABLE "Borrower"
ALTER COLUMN "borrowerRating" TYPE DOUBLE PRECISION,
ALTER COLUMN "borrowerRating" SET DEFAULT 0;
